### ISSUE TITLE
Board missions do not seem to restock every 10 seconds

### ISSUE THREAD

**Issue by Leroy8888** [HelixNebulaStudio/RiseOfTheDead#10] opened 2024-03-10 15:28 UTC

**Comment by MXKhronos** [comment] 2024-03-10 16:44
Okay, there's a mistake in the old trello post. The board missions will check for restock every 10s, but it should actually restock every hour.

There was a related bug however, when checking to restock, it also count the completed board missions when trying to restock, which will be fixed.

Made some changes for dev branch to the restock timer to 10s instead of 3600s on live branch. 

https://github.com/HelixNebulaStudio/RiseOfTheDead/commit/6b3e8a46847aea910f298d90fb73bee722042bad

Close this issue if you deem it fixed. I tested it and it seemed like it works as intended.

**Comment by Leroy8888** [comment] 2024-03-12 00:23
Seems like the mission timer is now 10 seconds instead of 5 minutes in dev branch. The missions also do not seem to restock every 10 seconds (but that likely is because the value is within another line of code).

**Comment by MXKhronos** [comment] 2024-03-13 00:28
Yep, fixed the incorrect value.

**Closed by MXKhronos** 2024-03-13 00:28 UTC
Labels: bug, w0t, dev-branch
