### ISSUE TITLE
bug with "time for an upgrade quest"

### ISSUE THREAD

**Issue by MemenTheMeme** [HelixNebulaStudio/RiseOfTheDead#689] opened 2024-09-11 02:18 UTC
quest stage "check the requirements for to build a pistol damage mod" does not progress after clicking the mod. crafting the mod does not progress it either. issue is on main branch, and was fine before patch

**Comment by MemenTheMeme** [comment] 2024-09-11 02:31
not sure if im able to, but this should probably be marked as important since not completing this quest bars players from actually leaving the starting area lol

**Comment by Leroy8888** [comment] 2024-09-11 21:53
Duplicate of #686. Appears to be a visual bug which can be completed if the mod is placed on the weapon (or not) and then upgraded. Does **not** indicate that this isn't severe as new players wouldn't know how to do so yet.

**Closed by Leroy8888** 2024-09-11 21:53 UTC
