### ISSUE TITLE
Player Character moving slowly on their own in First-Person Mode

### ISSUE THREAD

**Issue by zkkuu** [HelixNebulaStudio/RiseOfTheDead#484] opened 2024-06-11 22:03 UTC
If a player goes into first-person mode, their character will, for some reason, slowly move backwards on their own. More noticeable if the player equips an item; it doesn't matter what item it is, and they will move forward instead of moving backwards.

**Comment by MrGarrettFerret** [comment] 2024-06-12 02:30
Duplicate of https://github.com/HelixNebulaStudio/RiseOfTheDead/issues/482

**Closed by MrGarrettFerret** 2024-06-12 02:30 UTC
