### ISSUE TITLE
W.D. Mall Lighting

### ISSUE THREAD

**Issue by zkkuu** [HelixNebulaStudio/RiseOfTheDead#562] opened 2024-07-01 15:16 UTC
Is W.D. Mall supposed to be unnaturally bright compared to what it used to be and other worlds, or is it a bug that has been sticking around for a while?

**Comment by Leroy8888** [comment] 2024-07-01 17:45
needs a bit of clarification, is this a duplicate of #532 ?

**Comment by zkkuu** [comment] 2024-07-02 00:23
Back then, W.D. Mall used to appear much darker than it is now, which can be proven in a couple of ways.

The obvious one is the outside; even if you set your graphics to maxixum, you would not have any trouble looking around and seeing everything clearly at night compared to the rest of the four worlds. Another one is that if you compare the inside of the mall in W.D. Mall to during Awoken the Bear, the mall would actually appear with its old lighting in the latter.

If it's not clear enough, then let's look at the W.D. Mall boss arenas in W.D. Mall and BioX Research, where it also still uses the lighting I mentioned earlier.

![zomborg](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/171686799/65819d13-8486-4287-8932-2006f5c2bc40)
![billies](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/171686799/fd70d35d-f8b7-48c7-a2d2-bdc9ec62ec5b)
![hectorshot](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/171686799/ea3caa65-0a98-4b79-9cce-8e0ce59c3b69)

As you can see between the comparisons, the second image of each arena, which was captured in BioX Research, appeared darker than the first.

**Comment by zkkuu** [comment] 2024-07-02 00:30
Now, about https://github.com/HelixNebulaStudio/RiseOfTheDead/issues/532, although the issue you mentioned here is not a duplicate, it is related to the lighting strike feature included in it.

If you remember, during Slaughterfest events, there was a lighting strike feature that occurred every once in a while on a server. If a lighting strike happened to occur in W.D. Mall during that time, it would actually return to its old lighting.

No evidence to back this up because the most recent Slaughterfest event was... well, 9 months ago.

**Comment by MXKhronos** [comment] 2024-07-02 08:30
Each arena has their lighting adjusted a while back independent to WD Mall's lighting. WD Mall's lighting is a bit brighter than other worlds with a bit more ambience lights around the mall.

**Closed** 2024-07-04 19:05 UTC
