### ISSUE TITLE
Vindicative treasure problem

### ISSUE THREAD

**Issue by Rookie21333** [HelixNebulaStudio/RiseOfTheDead#251] opened 2024-04-27 09:02 UTC
i dont know if the problem is during vindicative treasure but my friend got frustrated since he cant get into the raid and getting stuck under the map.

btw heres the video my friend sent me:
https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/166785454/c52816d8-5f95-4263-9ec4-7fb35508282c

**Comment by Rookie21333** [comment] 2024-04-28 01:04
![Screenshot (140)](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/166785454/bf367f1c-edb9-46d6-bd46-7282e5454793)

**Comment by Leroy8888** [comment] 2024-04-29 14:34
Duplicate of #245

**Closed by Leroy8888** 2024-04-29 14:34 UTC
Labels: duplicate, live-branch, dev-branch
