### ISSUE TITLE
Conquerer's Haki Added? (Zombies disappear when you get into close proximity with them.) Might be severe. 

### ISSUE THREAD

**Issue by starlintons** [HelixNebulaStudio/RiseOfTheDead#543] opened 2024-06-25 16:42 UTC
https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/171533555/a8777e4b-0068-4cca-bd46-cc43043f99cf

Does not seem to effect all the zombies, but a good chunk of them just disappear.

**Comment by Leroy8888** [comment] 2024-06-25 22:01
Is this an issue in all worlds? Including raids and survivals?

**Comment by starlintons** [comment] 2024-06-25 22:23
Don't know, only tested in community as of now. Although I've seen other people in global chat complaining about the same issue, probably in other places.

**Comment by Leroy8888** [comment] 2024-06-25 23:16
This issue is exclusive to residentials. See mentioned issue.

**Comment by ShatteredVoidCrystal** [comment] 2024-06-28 07:11
hes hacking this has to me 1000000% kill aura 💯💯💯

**Comment by MXKhronos** [comment] 2024-06-30 13:29
Does this still happen in `2.1.16`?

**Comment by MrPigZ** [comment] 2024-06-30 17:43
I havent experienced this after 2.1.16 update.

**Comment by Leroy8888** [comment] 2024-06-30 22:21
This issue should be fixed in the branch version (and seems to be) as it was tied to issue #541. A commit (99bebe1) was done to fix this issue. 

This issue was caused by Nate, which constantly seemed to respawn when attempting to attack Robert or Joseph. When this occured, zombies that would agro would despawn. If Nate was busy shooting either Robert or Joseph during this, the zombies wouldn't despawn.

**Closed by Leroy8888** 2024-06-30 22:21 UTC
Labels: bug, w0t, moderate, live-branch
