### ISSUE TITLE
Ornaments Grand Garand usable is unavailable

### ISSUE THREAD

**Issue by rafaderren** [HelixNebulaStudio/RiseOfTheDead#831] opened 2024-12-25 15:08 UTC
![image](https://github.com/user-attachments/assets/c37ac4ea-0ce5-4127-81fe-b34c9e6ef04e)

**Comment by MrGarrettFerret** [comment] 2024-12-25 18:30
Duplicate of https://github.com/HelixNebulaStudio/RiseOfTheDead/issues/830

**Closed** 2024-12-25 18:30 UTC
